namespace IisLogParserArcGIS.Reports.Rendering;

/// <summary>
/// Fixed display metadata baked into every generated page's footer.
/// </summary>
internal static class DashboardMetadata
{
    /// <summary>
    /// The tool name shown in every page's "Generated by" footer line.
    /// </summary>
    public const string ToolName = "IisLogParserArcGIS";
}
