using System.Globalization;
using System.Net;
using System.Text;

namespace IisLogParserArcGIS.Reports.Rendering;

/// <summary>
/// Renders the shared HTML shell - header, sidebar, footer - every Dashboard page reuses, per ticket 01's site
/// map. Every page is a self-contained static file, so all links (the sidebar, the brand, the shared stylesheet)
/// are computed relative to <see cref="PageShellRequest.OutputRelativePath"/>'s own depth rather than
/// root-absolute, so the Dashboard also works when opened directly from disk rather than served over HTTP.
/// </summary>
public static class PageShellRenderer
{
    private const string TimestampFormat = "yyyy-MM-dd HH:mm:ss 'UTC'";

    /// <summary>
    /// Renders <paramref name="request"/>'s body content wrapped in the shared page shell.
    /// </summary>
    /// <param name="request">The page to render.</param>
    /// <returns>The complete HTML document.</returns>
    public static string Render(PageShellRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var rootPrefix = RelativeLinkHelper.ComputeRootPrefix(request.OutputRelativePath);
        var sidebarContext = new SidebarRenderContext(request.ActiveHref, rootPrefix);
        var sidebarHtml = RenderSidebarNodes(DashboardSidebar.BuildTree(request.IncludedRoots), sidebarContext, "sidebar");
        var timestampText = request.GeneratedAtUtc.UtcDateTime.ToString(TimestampFormat, CultureInfo.InvariantCulture);
        var googleChartsLoaderTag = request.RequiresGoogleCharts
            ? """<script src="https://www.gstatic.com/charts/loader.js"></script>"""
            : string.Empty;
        var chartScriptTags = $"""{googleChartsLoaderTag}<script src="{rootPrefix}assets/dashboard.js"></script>""";

        return $"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{WebUtility.HtmlEncode(request.Title)}</title>
            <link rel="stylesheet" href="{rootPrefix}assets/site.css">
            {chartScriptTags}
            </head>
            <body>
            <header class="dashboard-header">
            <a class="brand" href="{rootPrefix}index.html">ArcGIS IIS Log Reports</a>
            </header>
            <div class="dashboard-layout">
            <nav class="dashboard-sidebar">
            {sidebarHtml}
            </nav>
            <main class="dashboard-content">
            {request.BodyHtml}
            </main>
            </div>
            <footer class="dashboard-footer">
            <p>Generated by <a href="https://github.com/jayftee" target="_blank" rel="noopener noreferrer">jayftee</a>'s {DashboardMetadata.ToolName} on {timestampText}</p>
            </footer>
            </body>
            </html>
            """;
    }

    private static string RenderSidebarNodes(IReadOnlyList<SidebarNode> nodes, SidebarRenderContext context, string parentKey)
    {
        var html = new StringBuilder();
        html.Append("<ul>");

        foreach (var node in nodes)
        {
            html.Append("<li>");
            html.Append(node.Children.Count > 0
                ? RenderCollapsibleGroup(node, context, parentKey)
                : RenderSidebarEntry(node, context));
            html.Append("</li>");
        }

        html.Append("</ul>");
        return html.ToString();
    }

    /// <summary>
    /// Renders one group as a native <c>&lt;details&gt;</c> disclosure, auto-expanded when it sits on the path to
    /// <see cref="SidebarRenderContext.ActiveHref"/>. <paramref name="parentKey"/> - the ancestor-title path down
    /// to this group's own parent - becomes the <c>&lt;details name&gt;</c> shared by this group and its
    /// siblings, so opening one closes the others natively (no JavaScript): the sidebar never grows past one
    /// open branch per level.
    /// </summary>
    private static string RenderCollapsibleGroup(SidebarNode node, SidebarRenderContext context, string parentKey)
    {
        var isOpen = ContainsActiveDescendant(node, context.ActiveHref);
        var openAttribute = isOpen ? " open" : string.Empty;
        var openClass = isOpen ? " class=\"is-open\"" : string.Empty;
        var groupName = WebUtility.HtmlEncode(parentKey);
        var encodedTitle = WebUtility.HtmlEncode(node.Title);
        var childKey = $"{parentKey}/{node.Title}";
        var childrenHtml = RenderSidebarNodes(node.Children, context, childKey);

        return $"<details name=\"{groupName}\"{openAttribute}><summary{openClass}>{encodedTitle}</summary>{childrenHtml}</details>";
    }

    private static bool ContainsActiveDescendant(SidebarNode node, string activeHref)
    {
        if (string.Equals(node.Href, activeHref, StringComparison.Ordinal))
        {
            return true;
        }

        return node.Children.Any(child => ContainsActiveDescendant(child, activeHref));
    }

    private static string RenderSidebarEntry(SidebarNode node, SidebarRenderContext context)
    {
        var encodedTitle = WebUtility.HtmlEncode(node.Title);

        if (node.Href is null)
        {
            return $"<span>{encodedTitle}</span>";
        }

        var isActive = string.Equals(node.Href, context.ActiveHref, StringComparison.Ordinal);
        var cssClass = isActive ? " class=\"active\"" : string.Empty;
        var href = WebUtility.HtmlEncode(context.RootPrefix + node.Href);

        return $"<a href=\"{href}\"{cssClass}>{encodedTitle}</a>";
    }

    /// <summary>
    /// The two values every recursive sidebar-rendering call needs but never varies within one page's render -
    /// bundled so the recursive helpers stay within this repo's argument-count limit.
    /// </summary>
    private readonly record struct SidebarRenderContext(string ActiveHref, string RootPrefix);
}
